# Generated by Django 4.2 on 2023-04-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curret_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
